service: trending-stories-gcf

provider:
  name: google
  stage: dev
  runtime: nodejs8
  region: asia-east2
  project: trending-stories-240503
  credentials: /app/keys/google.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  proxy128:
    events:
      - http: path
    handler: proxy128
    memorySize: 128
    timeout: 60s
  proxy256:
    events:
      - http: path
    handler: proxy256
    memorySize: 256
    timeout: 60s
  proxy512:
    events:
      - http: path
    handler: proxy512
    memorySize: 512
    timeout: 60s
  parse256:
    events:
      - http: path
    handler: parse256
    memorySize: 256
    timeout: 60s
  parse512:
    events:
      - http: path
    handler: parse512
    memorySize: 512
    timeout: 60s
  parse1024:
    events:
      - http: path
    handler: parse1024
    memorySize: 1024
    timeout: 60s
